name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
