name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  REGION:
    description: 'AWS region'
  CLUSTER_NAME:
    description: 'K8s cluster name'
  CMD:
    describe: 'kubectl command to execute'
runs:
  using: 'docker'
  image: 'Dockerfile'
  pre-entrypoint: 'chmod +x entrypoint.sh'
  entrypoint: 'entrypoint.sh'
  args:
    - ${{ inputs.REGION }}
    - ${{ inputs.CLUSTER_NAME }}
    - ${{ inputs.CMD }}
