name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  REGION:
    description: 'AWS region'
  CLUSTER_NAME:
    description: 'K8s cluster name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REGION: ${{ inputs.REGION }}
    CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
