name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
inputs:
  cluster-name:
    description: 'the cluster name'
    require: true
    default: 'ck_new'

runs:
  using: 'composite'
  steps:
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install awscli
      shell: bash
      run: pip install awscli

    - name: get kubeconfig
      shell: bash
      run: aws eks update-kubeconfig --name ${{ inputs.cluster-name }}

    - uses: azure/setup-kubectl@v2.1
