name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
inputs:
  cluster-name:
    description: 'the cluster name'
    require: true
    default: 'ck_new'

runs:
  using: 'composite'
  steps:
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install awscli
      shell: bash
      run: pip install -U awscli

    - name: get kubeconfig
      shell: bash
      run: aws eks update-kubeconfig --name ${{ inputs.cluster-name }}

    - name: install kubectl fixed version
      shell: bash
      run: |
        curl -sLO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /bin

